config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :ideas do
    resources :comments
    resources :joins, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  
  root 'ideas#index'

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
  
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :joins, dependent: :destroy
  has_many :users, through: :joins

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  delegate :name_display, to: :user, prefix: true

  validates :title, :description, 
              presence: {message: "must be provided"},
              uniqueness: {message: "must be unique"}


end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :joins, dependent: :destroy
  has_many :joined_ideas, through: :joins, source: :idea

  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea


  def name_display
    if first_name || last_name
      "#{first_name} #{last_name}".squeeze(" ").strip.capitalize
    else
      email
    end  
  end
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @idea    = Idea.find(params[:idea_id])
    @comment      = @idea.comments.new(comment_params)
    @idea.user = current_user
    if @comment.save
      redirect_to @idea, notice: "Comment created successfully"
    else
      render "/ideas/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  def index
    @ideas = Idea.all
    @idea = Idea.new
  end

  
  def show
    @comment = Comment.new
    @join =@idea.joins.where(user: current_user).first
    @like =@idea.likes.where(user: current_user).first
    @idea.user = current_user
  end

  def new
    @idea = Idea.new
  end

  def edit
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created.' 
    else
      flash.now[:alert] = "Problem saving idea"
      render :new 
    end
  end
  def update
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.' 
  end

  private
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def idea_params
      params.require(:idea).permit(:title, :description)
    end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController

  before_action :authenticate_user!, :find_idea

  def create
    @join      = @idea.joins.new
    @join.user = current_user
    
    if current_user.id == @idea.user_id
      redirect_to @idea, alert: "you can't join your own idea"
    elsif @join.save
      redirect_to @idea, notice: "i love this idea"
    else
      redirect_to @idea, alert: "couldn't join"
    end
  end

  def destroy
    @join      = current_user.joins.find params[:id]
    if @join.destroy
      redirect_to @idea, notice: "Disjoined"
    else
      redirect_to @idea, alert: "couldn't Disjoin"
    end
  end

  def find_idea
    @idea      = Idea.find(params[:idea_id])

  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  before_action :authenticate_user!, :find_idea

  def create
    @like      = @idea.likes.new
    @like.user = current_user

    if current_user.id == @idea.user_id
      redirect_to @idea, alert: "you can't like your own idea"
    elsif @like.save
      redirect_to @idea, notice: "Thanks for liking this idea"
    else
      redirect_to @idea, alert: "you already liked this idea"
    end
  end

  def destroy
    @like      = current_user.likes.find params[:id]
    if @like.destroy
      redirect_to @idea, notice: "Disliked"
    else
      redirect_to @idea, alert: "couldn't Dislike"
    end
  end

  def find_idea
    @idea      = Idea.find(params[:idea_id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/ideas/_form.html.haml
#formfornewidea{style: "display:none;"}
  = form_for(@idea) do |f|
    / - if @idea.errors.any?
    /   #error_explanation
    /     %h2
    /       = pluralize(@idea.errors.count, "error")
    /       prohibited this idea from being saved:
    /     %ul
    /       - @idea.errors.full_messages.each do |message|
    /         %li= message
    .field
      = f.label :title
      %br/
      = f.text_field :title
    .field
      = f.label :description
      %br/
      = f.text_area :description
    .actions
      = f.submit

app/views/ideas/edit.html.haml
%h1 Editing idea
= render 'form'
= link_to 'Show', @idea

app/views/ideas/index.html.haml
%h5 
  Idea Factory
  .pull-right= link_to 'New Idea', "javascript:void(0)", class: "btn btn-primary newidea"
%hr

= render 'form'

- @ideas.each do |idea|
  %h3
    %strong= idea.title
  %br/
  %p= idea.description
  
  %p By: #{idea.user.email}

  %p.pull-right Members: #{idea.joins.length}  Likes: #{idea.likes.length} 

  = link_to 'Show', idea
  = link_to 'Edit', edit_idea_path(idea)
  = link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' }
  %hr  
%br/

app/views/ideas/new.html.haml
%h1 New idea
= render 'form'

app/views/ideas/show.html.haml
%p
  %strong Title:
  = @idea.title
%p
  %strong Description:
  = @idea.description
= link_to 'Edit', edit_idea_path(@idea)

- if user_signed_in?

  - if @idea.joins.exists?(user_id: current_user.id)
    = link_to "<i class='glyphicon glyphicon-star'></i>".html_safe, [@idea, @join], class: "btn btn-default btn-sm", method: :delete
  - else
    = link_to "<i class='glyphicon glyphicon-star-empty'></i>".html_safe, [@idea, Join.new], class: "btn btn-default btn-sm", method: :post

- if user_signed_in?
  - if @idea.likes.exists?(user_id: current_user.id)
    = link_to "<i class='glyphicon glyphicon-thumbs-up'></i>".html_safe, [@idea, @like], class: "btn btn-primary btn-sm", method: :delete
  - else
    = link_to "<i class='glyphicon glyphicon-thumbs-up'></i>".html_safe, [@idea, Like.new], class: "btn btn-default btn-sm", method: :post


%hr

%h2.sub-title Submit a Comment for this Idea

= form_for [@idea, @comment] do |f|
  = f.text_area :body
  = f.submit

%hr

%h4 These users joined this idea:

- @idea.comments.each do |comment|
  = comment.body
  %br


- @idea.joins.each do |join|
  %p= User.where(id: join.user_id).first.email
 
   
%br/

 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title IdeaFactory
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
  
    %nav.nav.navbar-default
      .container-fluid
        %ul.nav.navbar-nav
          %li= link_to "Home", root_path
        
        %ul.nav.navbar-nav.pull-right
          - if user_signed_in?
            %li= link_to current_user.name_display, edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Sign In", new_user_session_path
    
    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - elsif flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      = yield     